--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO py3_gj_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO py3_gj_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO py3_gj_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO py3_gj_user;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO py3_gj_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO py3_gj_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO py3_gj_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO py3_gj_user;

--
-- Name: myapp_product; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.myapp_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    price numeric(10,2) NOT NULL,
    description text NOT NULL,
    quantity_in_stock integer NOT NULL,
    image character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id bigint,
    CONSTRAINT myapp_product_quantity_in_stock_check CHECK ((quantity_in_stock >= 0))
);


ALTER TABLE public.myapp_product OWNER TO py3_gj_user;

--
-- Name: myapp_product_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.myapp_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myapp_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myapp_purchase; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.myapp_purchase (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    returned boolean NOT NULL,
    CONSTRAINT myapp_purchase_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.myapp_purchase OWNER TO py3_gj_user;

--
-- Name: myapp_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.myapp_purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myapp_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myapp_return; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.myapp_return (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    purchase_id bigint NOT NULL,
    CONSTRAINT myapp_return_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.myapp_return OWNER TO py3_gj_user;

--
-- Name: myapp_return_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.myapp_return ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myapp_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myapp_user; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.myapp_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    birth_date date,
    avatar character varying(100),
    wallet numeric(10,2) NOT NULL,
    is_admin boolean NOT NULL
);


ALTER TABLE public.myapp_user OWNER TO py3_gj_user;

--
-- Name: myapp_user_groups; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.myapp_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.myapp_user_groups OWNER TO py3_gj_user;

--
-- Name: myapp_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.myapp_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myapp_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myapp_user_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.myapp_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myapp_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: myapp_user_user_permissions; Type: TABLE; Schema: public; Owner: py3_gj_user
--

CREATE TABLE public.myapp_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.myapp_user_user_permissions OWNER TO py3_gj_user;

--
-- Name: myapp_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: py3_gj_user
--

ALTER TABLE public.myapp_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.myapp_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add product	9	add_product
26	Can change product	9	change_product
27	Can delete product	9	delete_product
28	Can view product	9	view_product
29	Can add purchase	8	add_purchase
30	Can change purchase	8	change_purchase
31	Can delete purchase	8	delete_purchase
32	Can view purchase	8	view_purchase
33	Can add return	7	add_return
34	Can change return	7	change_return
35	Can delete return	7	delete_return
36	Can view return	7	view_return
37	Can add icon	10	add_icon
38	Can change icon	10	change_icon
39	Can delete icon	10	delete_icon
40	Can view icon	10	view_icon
41	Can add Token	11	add_token
42	Can change Token	11	change_token
43	Can delete Token	11	delete_token
44	Can view Token	11	view_token
45	Can add Token	12	add_tokenproxy
46	Can change Token	12	change_tokenproxy
47	Can delete Token	12	delete_tokenproxy
48	Can view Token	12	view_tokenproxy
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
30aa1e3efe25aca9df99af5fe8181ecbafb37d8f	2025-02-01 19:15:16.046988+00	2
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-12-28 17:16:56.151044+00	3	admin2	1	[{"added": {}}]	6	2
2	2024-12-28 17:51:57.940915+00	1	ZARA	1	[{"added": {}}]	9	2
3	2024-12-28 17:55:13.570104+00	2	VERSACE	1	[{"added": {}}]	9	2
4	2024-12-28 17:56:12.312218+00	3	GUCCI	1	[{"added": {}}]	9	2
5	2024-12-28 17:57:20.958023+00	4	PRADA	1	[{"added": {}}]	9	2
6	2024-12-28 17:59:11.25524+00	5	Calvin Klein	1	[{"added": {}}]	9	2
7	2024-12-28 18:01:26.567423+00	6	PRADA	1	[{"added": {}}]	9	2
8	2024-12-28 18:02:30.93265+00	7	GUCCI	1	[{"added": {}}]	9	2
9	2024-12-28 18:03:51.380846+00	8	Calvin Klein	1	[{"added": {}}]	9	2
10	2024-12-28 18:06:26.285915+00	1	admin2 - ZARA	1	[{"added": {}}]	8	2
11	2024-12-28 18:06:45.01015+00	1	admin2 - ZARA	1	[{"added": {}}]	7	2
12	2024-12-29 19:59:04.050179+00	1	ZARA	3		9	2
13	2024-12-29 20:00:36.749577+00	9	ZARA	1	[{"added": {}}]	9	2
14	2024-12-29 20:02:03.404361+00	10	ZARA	1	[{"added": {}}]	9	2
15	2024-12-29 20:03:19.977365+00	9	ZARA	3		9	2
16	2024-12-29 21:12:39.884914+00	11	fhxh	1	[{"added": {}}]	9	2
17	2024-12-29 21:24:40.531157+00	11	fhxh	3		9	2
18	2025-01-01 11:32:35.908133+00	10	ZARA	2	[{"changed": {"fields": ["Image"]}}]	9	2
19	2025-01-01 11:35:00.238339+00	8	Calvin Klein	2	[{"changed": {"fields": ["Image"]}}]	9	2
20	2025-01-01 11:35:42.375722+00	7	GUCCI	2	[{"changed": {"fields": ["Image"]}}]	9	2
21	2025-01-01 11:36:10.392215+00	6	PRADA	2	[{"changed": {"fields": ["Image"]}}]	9	2
22	2025-01-01 11:37:00.798333+00	5	Calvin Klein	2	[{"changed": {"fields": ["Image"]}}]	9	2
23	2025-01-01 11:37:33.818816+00	4	PRADA	2	[{"changed": {"fields": ["Image"]}}]	9	2
24	2025-01-01 11:37:48.220323+00	3	GUCCI	2	[{"changed": {"fields": ["Image"]}}]	9	2
25	2025-01-01 11:38:04.487458+00	2	VERSACE	2	[{"changed": {"fields": ["Image"]}}]	9	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	myapp	user
7	myapp	return
8	myapp	purchase
9	myapp	product
10	myapp	icon
11	authtoken	token
12	authtoken	tokenproxy
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-12-27 21:12:54.991466+00
2	contenttypes	0002_remove_content_type_name	2024-12-27 21:12:55.017228+00
3	auth	0001_initial	2024-12-27 21:12:55.090201+00
4	auth	0002_alter_permission_name_max_length	2024-12-27 21:12:55.102057+00
5	auth	0003_alter_user_email_max_length	2024-12-27 21:12:55.102057+00
6	auth	0004_alter_user_username_opts	2024-12-27 21:12:55.102057+00
7	auth	0005_alter_user_last_login_null	2024-12-27 21:12:55.116567+00
8	auth	0006_require_contenttypes_0002	2024-12-27 21:12:55.116567+00
9	auth	0007_alter_validators_add_error_messages	2024-12-27 21:12:55.116567+00
10	auth	0008_alter_user_username_max_length	2024-12-27 21:12:55.116567+00
11	auth	0009_alter_user_last_name_max_length	2024-12-27 21:12:55.132206+00
12	auth	0010_alter_group_name_max_length	2024-12-27 21:12:55.148071+00
13	auth	0011_update_proxy_permissions	2024-12-27 21:12:55.148071+00
14	auth	0012_alter_user_first_name_max_length	2024-12-27 21:12:55.163706+00
15	myapp	0001_initial	2024-12-27 21:12:55.24225+00
16	admin	0001_initial	2024-12-27 21:12:55.273497+00
17	admin	0002_logentry_remove_auto_add	2024-12-27 21:12:55.289518+00
18	admin	0003_logentry_add_action_flag_choices	2024-12-27 21:12:55.289518+00
19	sessions	0001_initial	2024-12-27 21:12:55.320778+00
20	myapp	0002_alter_user_birth_date	2024-12-27 21:26:27.443426+00
21	myapp	0003_product_alter_user_avatar_purchase_return	2024-12-28 17:28:44.321883+00
22	myapp	0004_remove_product_is_available	2024-12-28 17:41:53.606064+00
23	myapp	0005_icon_alter_purchase_created_at_and_more	2024-12-29 20:53:10.464119+00
24	myapp	0006_remove_icon_name	2024-12-29 21:01:41.6726+00
25	myapp	0007_delete_icon	2024-12-29 21:11:41.147734+00
26	myapp	0008_user_wallet	2024-12-30 20:13:33.679041+00
27	myapp	0009_alter_product_options_alter_user_wallet	2025-01-01 16:33:11.40735+00
28	myapp	0010_return_purchase_alter_return_updated_at	2025-01-03 15:05:30.215676+00
29	myapp	0011_alter_return_purchase	2025-01-04 18:20:07.566871+00
30	myapp	0012_user_is_admin	2025-01-05 14:16:32.108357+00
31	myapp	0013_alter_user_managers	2025-01-05 14:56:01.678063+00
32	myapp	0014_purchase_returned_alter_return_purchase	2025-01-05 20:40:36.790074+00
33	myapp	0015_alter_purchase_updated_at	2025-01-06 15:20:08.702529+00
34	authtoken	0001_initial	2025-01-29 20:28:01.284418+00
35	authtoken	0002_auto_20160226_1747	2025-01-29 20:28:01.346964+00
36	authtoken	0003_tokenproxy	2025-01-29 20:28:01.362709+00
37	authtoken	0004_alter_tokenproxy_options	2025-01-29 20:28:01.362709+00
38	myapp	0016_product_owner	2025-02-01 20:59:57.75284+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7ewcyz853qtnp9lqko6o1ledljoc85gk	.eJxVjMsOwiAQRf-FtSE8OjC4dO83EGBAqgaS0q6M_65NutDtPefcF_NhW6vfRl78TOzMFDv9bjGkR247oHtot85Tb-syR74r_KCDXzvl5-Vw_w5qGPVbIwqhAhUyagLS2aGKk4hIRhNZRFAOjA1kRXGgXQZBUjoTEwIKWQp7fwDL0Dcv:1tRHsW:030DuflwUwWsQMtbEUROAyyIkHNUYvu9v6rIw6un6i0	2025-01-10 21:28:16.368295+00
grystae507c7rhw9o0dpuy8clhb6w53d	.eJxVjMsOwiAQRf-FtSE8OjC4dO83EGBAqgaS0q6M_65NutDtPefcF_NhW6vfRl78TOzMFDv9bjGkR247oHtot85Tb-syR74r_KCDXzvl5-Vw_w5qGPVbIwqhAhUyagLS2aGKk4hIRhNZRFAOjA1kRXGgXQZBUjoTEwIKWQp7fwDL0Dcv:1tRzQd:-RnY3az3n1NTLVwXu5QwwoZ-RWVZ51OlFIpsOeLRjVg	2025-01-12 19:58:23.515744+00
2ruibqm2na7ryhf8brcnbjmj0g37sa96	.eJxVjDsOwjAQBe_iGllrx86Hkp4zRLt-Dg4gW4qTCnF3iJQC2jcz76VG3tY0bjUu4wx1VqZRp99RODxi3gnunG9Fh5LXZRa9K_qgVV8L4vNyuH8HiWv61hZkByfBg4YgHp1FADMgxruJXIzSU4uGjDXUg2CIfWc5kAhaO6n3ByOxOL0:1tacoS:MeeMt-M2FznxmlE6q1Wd2hjulMpN2QY43UUZq7eK-X4	2025-02-05 15:38:40.10644+00
vgnrpmubuz22y3mfs0ywhi7ouryyopns	.eJxVjMsOwiAQRf-FtSE8OjC4dO83EGBAqgaS0q6M_65NutDtPefcF_NhW6vfRl78TOzMFDv9bjGkR247oHtot85Tb-syR74r_KCDXzvl5-Vw_w5qGPVbIwqhAhUyagLS2aGKk4hIRhNZRFAOjA1kRXGgXQZBUjoTEwIKWQp7fwDL0Dcv:1tXQcO:0fkSfKyO0nWqVNba8X2ydFRu4vlYo1oJbMwzs6PtfO4	2025-01-27 20:01:00.484325+00
g6khbz16424v146r9la6bdf5eq0nzexl	.eJxVjEEOwiAQRe_C2hCmQOm4dN8zNDADUjWQlHZlvLsh6UK3_73332Lxx56Xo8VtWVlcBVhx-R2Dp2csnfDDl3uVVMu-rUF2RZ60yblyfN1O9-8g-5Z7bSwgaTtNIwdGRD3iAEBBQ0KwrBWjMck5F4FdCmQGFYkAFVBiHcXnC-7CN-c:1tfijH:1Sx7RwvaJkWjIrBTnDpwdFcwYmhU2umkxwk5X43vvPM	2025-02-19 16:58:23.009686+00
\.


--
-- Data for Name: myapp_product; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.myapp_product (id, name, price, description, quantity_in_stock, image, created_at, updated_at, owner_id) FROM stdin;
3	GUCCI	3000.00	Checkered Shirt./\r\nConsists of: cotton./\r\nSize: S./\r\nMen's	2	products/Frame_34_1.jpg	2024-12-28 17:56:12.30162+00	2025-01-20 18:49:29.091162+00	\N
5	Calvin Klein	2500.00	Vertical Striped Shirt./\r\nConsists of: cotton./\r\nSize: M./\r\nMen's	5	products/Frame_32_3_Xbsy6ca.jpg	2024-12-28 17:59:11.244712+00	2025-01-20 19:07:21.727975+00	\N
2	VERSACE	3000.00	Skinny Fit Jeans./\r\nConsists of: cotton./\r\nSize: XL./\r\nMen's	5	products/Frame_33_2.jpg	2024-12-28 17:55:13.555861+00	2025-01-20 18:20:41.500701+00	\N
4	PRADA	750.00	Sleeve Striped T-shirt./\r\nConsists of: cotton./\r\nSize: XL./\r\nMen's	4	products/Frame_38_2.jpg	2024-12-28 17:57:20.940766+00	2025-01-20 21:11:14.086291+00	\N
10	ZARA	1000.00	T-shirt with Tape Details.//\r\nConsists of: cotton./\r\nSize: XL../\r\nMen's	5	products/Frame_32.png	2024-12-29 20:02:03.383153+00	2025-02-05 16:51:42.669282+00	\N
6	PRADA	3000.00	Vertical Striped Shirt./\r\nConsists of: cotton./\r\nSize: L./\r\nMen's	3	products/Frame_32_3.jpg	2024-12-28 18:01:26.552396+00	2025-01-21 15:38:22.608804+00	\N
8	Calvin Klein	1000.00	Faded Skinny Jeans./\r\nConsists of: cotton./\r\nSize: XL./\r\nWomen's	2	products/Frame_38_3.jpg	2024-12-28 18:03:51.371609+00	2025-02-05 16:52:48.947885+00	\N
12	ZARA	1000.00		6		2025-02-05 18:02:20.479208+00	2025-02-05 18:02:20.48026+00	\N
7	GUCCI	5000.00	Loose Fit Bermuda Shorts./\r\nConsists of: cotton./\r\nSize: XL./\r\nWomen's	3	products/Frame_34_2.jpg	2024-12-28 18:02:30.917602+00	2025-01-22 15:37:56.496285+00	\N
13	ZARA	1000.00		4		2025-02-05 18:03:29.74153+00	2025-02-05 18:03:29.74153+00	\N
14	ZARA	1000.00		4		2025-02-05 18:04:00.354496+00	2025-02-05 18:04:00.354496+00	\N
15	ZARA	1000.00		7		2025-02-05 18:04:25.290136+00	2025-02-05 18:04:25.290136+00	\N
\.


--
-- Data for Name: myapp_purchase; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.myapp_purchase (id, quantity, created_at, updated_at, product_id, user_id, returned) FROM stdin;
37	1	2025-01-20 16:31:24.606601+00	2025-01-20 16:31:24.626892+00	7	11	f
38	1	2025-01-20 16:31:44.007046+00	2025-01-20 16:31:44.035115+00	6	11	f
39	1	2025-01-20 16:32:33.540526+00	2025-01-20 16:32:33.556002+00	5	11	f
100	1	2025-02-05 16:32:57.517455+00	2025-02-05 16:33:02.949445+00	10	14	t
85	3	2025-01-20 20:48:42.594241+00	2025-01-20 20:48:47.547739+00	8	5	t
\.


--
-- Data for Name: myapp_return; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.myapp_return (id, quantity, created_at, updated_at, product_id, user_id, purchase_id) FROM stdin;
\.


--
-- Data for Name: myapp_user; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.myapp_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, birth_date, avatar, wallet, is_admin) FROM stdin;
3	1	\N	t	admin2				f	t	2024-12-28 17:13:09+00	\N		0.00	f
4	pbkdf2_sha256$870000$VRSokse5fZpIdQG2msdKzo$it4k3Lrcp3Elw2NTHWrr7Km8ocIIVOMRgv376r9j9KQ=	\N	t	admin3				t	t	2025-01-03 15:06:04.72126+00	\N		10000.00	f
2	pbkdf2_sha256$870000$0fWjzux5CT0pO45a08dwqB$oyAKRN3/oY8Dx7ci35jEqycOsv5OgwY186JfdKagjns=	2025-02-05 16:52:33.914504+00	t	admin				t	t	2024-12-27 21:26:53.544118+00	\N		0.00	f
13	pbkdf2_sha256$870000$WQNMzVQXReSsqPm3WPHCxz$ioeWkn+CQkD8Gzv+H8cm6wjlorO/z/ejXnfRtVZ4KUo=	2025-02-05 15:26:04.335097+00	f	dina			dina@list.ru	f	t	2025-01-21 15:35:23.970352+00	\N		8000.00	f
14	pbkdf2_sha256$870000$tuX9W4G0GvlVWsGA96PjOU$Px7vwWGJtqlp+J7OZphVxfu06pd+b6bzoY9Mke1i800=	2025-02-05 16:52:58.808821+00	f	dina2				f	t	2025-02-05 15:34:53.204627+00	\N		6000.00	f
11	pbkdf2_sha256$870000$sh4UaYT0P4zjmZWkZ8TlRO$JsqojI9sv9KVG/Y1/z7EnKDFyeXofmuAmwiuhqODLcs=	2025-01-20 16:39:42.533107+00	f	Jana			evgenia@list.ru	f	t	2025-01-06 15:24:48.482266+00	\N		2500.00	f
8	pbkdf2_sha256$870000$pWuQiZZdIntVtsDUyMtLEa$vRZTvIezPDwmPCujCTzQUiX563pZXfFEhqqP2/TnGBo=	2025-01-05 16:29:24.014477+00	f	Evgeny33			evgen@list.ru	f	t	2025-01-05 16:29:21.864308+00	\N		10000.00	f
9	pbkdf2_sha256$870000$heMAhtsOBuF9yUNLftaKTw$EgLaNHx0ylvd6IyXKscwWtCDyFA5Aq9TSkmBjO0M7Zk=	2025-01-05 16:34:19.832204+00	f	Evgen23			evgen@list.ru	f	t	2025-01-05 16:34:17.683147+00	\N		10000.00	f
10	pbkdf2_sha256$870000$OtJQOJIPGXOevE4RGNs8mD$8hUUPnGMvjftcdGc3FlYxQA90AxwuBYTrrPqvBQaN/I=	2025-01-05 16:37:32.080557+00	f	Evgen33			evgen@list.ru	f	t	2025-01-05 16:37:29.752116+00	\N		10000.00	f
12	pbkdf2_sha256$870000$HqzRIaTGFplQMUsaRZEYAk$p8CM9GLhLWiNPVgpEZlGoaKo7kyHG4vHxtTlnsfs5tI=	2025-01-20 18:23:35.573419+00	f	Jana2			evgen@list.ru	f	t	2025-01-20 16:40:33.3722+00	\N		250.00	f
15	pbkdf2_sha256$870000$40fx5yYqpnybIEUrsDFuXz$memm+sxHnaiwfGMhLeTCOriMmg+QyNBuqjQzkLuMwgo=	2025-02-05 16:58:22.991188+00	f	dina3				f	t	2025-02-05 16:58:20.651888+00	\N		10000.00	f
7	pbkdf2_sha256$870000$7F4ZqcdHXaBKnqNGQUCet2$ZQYmUun6Bi+wXY/fTwgN0mV6lNe20tIcJzDYyzJS9vM=	2025-01-20 19:28:07.627446+00	f	Evgeny22			mepraha2015@gmail.com	f	t	2025-01-05 16:05:34.196598+00	\N		500.00	f
5	pbkdf2_sha256$870000$uP0BLFpfFPGIWDhUOrGHJs$wlDltwL49S2SRe13tjvdW6lvPF6pWfNfWx+vglWtAZc=	2025-01-20 21:10:03.51954+00	f	Evgen			evgen8276@list.ru	f	t	2025-01-05 15:55:39.415273+00	\N		755.00	f
6	pbkdf2_sha256$870000$Ni96rqzWJt56rg4Xndc46K$QF6Daf4kv3yP7ovGCUDHhotVV1CXbgLY2i1L0huwjSo=	2025-01-20 18:42:56.362523+00	f	Evgeny2			mej@example.com	f	t	2025-01-05 15:57:12.985908+00	\N		1000.00	f
\.


--
-- Data for Name: myapp_user_groups; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.myapp_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: myapp_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: py3_gj_user
--

COPY public.myapp_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 25, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 38, true);


--
-- Name: myapp_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.myapp_product_id_seq', 45, true);


--
-- Name: myapp_purchase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.myapp_purchase_id_seq', 103, true);


--
-- Name: myapp_return_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.myapp_return_id_seq', 91, true);


--
-- Name: myapp_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.myapp_user_groups_id_seq', 1, false);


--
-- Name: myapp_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.myapp_user_id_seq', 15, true);


--
-- Name: myapp_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: py3_gj_user
--

SELECT pg_catalog.setval('public.myapp_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: myapp_product myapp_product_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_product
    ADD CONSTRAINT myapp_product_pkey PRIMARY KEY (id);


--
-- Name: myapp_purchase myapp_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_purchase
    ADD CONSTRAINT myapp_purchase_pkey PRIMARY KEY (id);


--
-- Name: myapp_return myapp_return_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_return
    ADD CONSTRAINT myapp_return_pkey PRIMARY KEY (id);


--
-- Name: myapp_user_groups myapp_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_groups
    ADD CONSTRAINT myapp_user_groups_pkey PRIMARY KEY (id);


--
-- Name: myapp_user_groups myapp_user_groups_user_id_group_id_1ef5feb7_uniq; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_groups
    ADD CONSTRAINT myapp_user_groups_user_id_group_id_1ef5feb7_uniq UNIQUE (user_id, group_id);


--
-- Name: myapp_user myapp_user_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user
    ADD CONSTRAINT myapp_user_pkey PRIMARY KEY (id);


--
-- Name: myapp_user_user_permissions myapp_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_user_permissions
    ADD CONSTRAINT myapp_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: myapp_user_user_permissions myapp_user_user_permissions_user_id_permission_id_13102f46_uniq; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_user_permissions
    ADD CONSTRAINT myapp_user_user_permissions_user_id_permission_id_13102f46_uniq UNIQUE (user_id, permission_id);


--
-- Name: myapp_user myapp_user_username_key; Type: CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user
    ADD CONSTRAINT myapp_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: myapp_product_owner_id_6ccfc2e2; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_product_owner_id_6ccfc2e2 ON public.myapp_product USING btree (owner_id);


--
-- Name: myapp_purchase_product_id_8d5d25ef; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_purchase_product_id_8d5d25ef ON public.myapp_purchase USING btree (product_id);


--
-- Name: myapp_purchase_user_id_f3faeaab; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_purchase_user_id_f3faeaab ON public.myapp_purchase USING btree (user_id);


--
-- Name: myapp_return_product_id_119fcc7f; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_return_product_id_119fcc7f ON public.myapp_return USING btree (product_id);


--
-- Name: myapp_return_purchase_id_634ba8a8; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_return_purchase_id_634ba8a8 ON public.myapp_return USING btree (purchase_id);


--
-- Name: myapp_return_user_id_3224b2e7; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_return_user_id_3224b2e7 ON public.myapp_return USING btree (user_id);


--
-- Name: myapp_user_groups_group_id_488eb0fb; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_user_groups_group_id_488eb0fb ON public.myapp_user_groups USING btree (group_id);


--
-- Name: myapp_user_groups_user_id_925f87c5; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_user_groups_user_id_925f87c5 ON public.myapp_user_groups USING btree (user_id);


--
-- Name: myapp_user_user_permissions_permission_id_4657f93a; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_user_user_permissions_permission_id_4657f93a ON public.myapp_user_user_permissions USING btree (permission_id);


--
-- Name: myapp_user_user_permissions_user_id_3f0ef5c3; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_user_user_permissions_user_id_3f0ef5c3 ON public.myapp_user_user_permissions USING btree (user_id);


--
-- Name: myapp_user_username_a1e18371_like; Type: INDEX; Schema: public; Owner: py3_gj_user
--

CREATE INDEX myapp_user_username_a1e18371_like ON public.myapp_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_myapp_user_id FOREIGN KEY (user_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_myapp_user_id FOREIGN KEY (user_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_product myapp_product_owner_id_6ccfc2e2_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_product
    ADD CONSTRAINT myapp_product_owner_id_6ccfc2e2_fk_myapp_user_id FOREIGN KEY (owner_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_purchase myapp_purchase_product_id_8d5d25ef_fk_myapp_product_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_purchase
    ADD CONSTRAINT myapp_purchase_product_id_8d5d25ef_fk_myapp_product_id FOREIGN KEY (product_id) REFERENCES public.myapp_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_purchase myapp_purchase_user_id_f3faeaab_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_purchase
    ADD CONSTRAINT myapp_purchase_user_id_f3faeaab_fk_myapp_user_id FOREIGN KEY (user_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_return myapp_return_product_id_119fcc7f_fk_myapp_product_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_return
    ADD CONSTRAINT myapp_return_product_id_119fcc7f_fk_myapp_product_id FOREIGN KEY (product_id) REFERENCES public.myapp_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_return myapp_return_purchase_id_634ba8a8_fk_myapp_purchase_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_return
    ADD CONSTRAINT myapp_return_purchase_id_634ba8a8_fk_myapp_purchase_id FOREIGN KEY (purchase_id) REFERENCES public.myapp_purchase(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_return myapp_return_user_id_3224b2e7_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_return
    ADD CONSTRAINT myapp_return_user_id_3224b2e7_fk_myapp_user_id FOREIGN KEY (user_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_user_groups myapp_user_groups_group_id_488eb0fb_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_groups
    ADD CONSTRAINT myapp_user_groups_group_id_488eb0fb_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_user_groups myapp_user_groups_user_id_925f87c5_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_groups
    ADD CONSTRAINT myapp_user_groups_user_id_925f87c5_fk_myapp_user_id FOREIGN KEY (user_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_user_user_permissions myapp_user_user_perm_permission_id_4657f93a_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_user_permissions
    ADD CONSTRAINT myapp_user_user_perm_permission_id_4657f93a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: myapp_user_user_permissions myapp_user_user_permissions_user_id_3f0ef5c3_fk_myapp_user_id; Type: FK CONSTRAINT; Schema: public; Owner: py3_gj_user
--

ALTER TABLE ONLY public.myapp_user_user_permissions
    ADD CONSTRAINT myapp_user_user_permissions_user_id_3f0ef5c3_fk_myapp_user_id FOREIGN KEY (user_id) REFERENCES public.myapp_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO py3_gj_user;


--
-- PostgreSQL database dump complete
--

