# Generated by Django 5.1.4 on 2024-12-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_icon_alter_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='name',
        ),
    ]
