# Generated by Django 5.1.4 on 2024-12-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_icon_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
