# Generated by Django 5.1.4 on 2025-01-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_product_options_alter_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase'),
        ),
        migrations.AlterField(
            model_name='return',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
