# Generated by Django 5.1.4 on 2025-01-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_return_purchase_alter_return_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='purchase',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.purchase'),
        ),
    ]
